### ISSUE TITLE
plots with multi-sets

### ISSUE THREAD

**Issue by SolayMane** [gdmcdonald/plotVenn#9]
I appreciate you package, is there any possibility to improve the presentation ?

![image](https://user-images.githubusercontent.com/22656460/112500468-15c5f000-8d91-11eb-82e2-c07756da2541.png)

**Comment by gdmcdonald** [comment]
This package just wraps up functions from the eulerr package. I'd suggest you either look at the arguments in that package, or alternately, your data looks like it would go well in an UpSet plot, like in this example: https://www.r-bloggers.com/2020/04/upset-plots/
